### ISSUE TITLE
Oceanic place is land type in the package

### ISSUE THREAD

**Issue by zxdawn** [gauteh/roaring-landmask#23]
Hi, I have tested this package for one point over the ocean and it returns `True` which means it's over land.

```
import numpy as np
from roaring_landmask import RoaringLandmask

roaring = RoaringLandmask.new()

on_land = roaring.contains_many(np.array([52.298012]), np.array([45.525833]))
print(on_land)
```

![image](https://github.com/gauteh/roaring-landmask/assets/30388627/a79ff46b-c0b3-4919-9e2e-5229af6d71ae)

**Comment by knutfrode** [comment]
Hi,
(Roaring) Landmask is based on GSHHG, which considers Caspian Sea as a lake, and not ocean.
However, if you have an ocean model with landmask, you can use this for the simulations, as demonstrated here:
https://opendrift.github.io/gallery/example_model_landmask.html

**Comment by zxdawn** [comment]
Thanks! I find cartopy also works well:

```
import cartopy.feature as cfeature
from shapely.geometry import Point

land_50m = cfeature.NaturalEarthFeature('physical','land','50m')

land_polygons = list(land_50m.geometries())

any([polygon.contains(Point(52.298012, 45.525833)) for polygon in land_polygons])
```

**Comment by zxdawn** [comment]
In case anyone is interested, I have written an example on [stackoverflow](https://stackoverflow.com/a/77389561/7347925). It's really fast to get results with geopandas.

**Comment by gauteh** [comment]
👍 naturalearth is less accurate than gshhg. You could try and add your examples as a benchmark to compare the methods: https://github.com/gauteh/roaring-landmask/blob/main/tests/test_roaring.py

**Comment by zxdawn** [comment]
@gauteh Thanks! This [answer](https://stackoverflow.com/a/74540710/7347925) has a nice comparison between natural earth and gshhg:

![image](https://github.com/gauteh/roaring-landmask/assets/30388627/22ad1484-7f8d-4b8e-98b6-fad567af3843)

**Comment by gauteh** [comment]
roaring-landmask uses only the full GSHHG. If you want to do accurate benchmarks it is better to do it like the code I linked to.
