### ISSUE TITLE
no assets on musl-linux: Bug in version 0.9.0: FileNotFoundError: cannot find mask 

### ISSUE THREAD

**Issue by davincent-ucl** [gauteh/roaring-landmask#32]
Hello,
It seems that there is an issue with version 0.9.0 released yesterday. Creating a new mask results in a FileNotFoundError.
```bash
>>> from roaring_landmask import RoaringLandmask
>>> l = RoaringLandmask.new()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: cannot find mask
```

**Comment by gauteh** [comment]
Hi, how did you install the package?

ping: @TheSylex

**Comment by davincent-ucl** [comment]
The package is a requirement from opendrift and is installed during the installation of opendrift.
 I got the same issue when installing roaring_landmask with pip install
 specifying the version 0.8.0 fix the issue

**Comment by gauteh** [comment]
Did you install opendrift using pip?

**Comment by davincent-ucl** [comment]
yes

**Comment by gauteh** [comment]
Which platform are you on? We usually recommend conda for opendrift, because dependencies are easier to get right: https://opendrift.github.io/install.html

There's another issue with enough space on pypi for this package: #31 . Some platforms got a version without the assets included, so I have yanked version 0.9.0 until this issue is fixed.

**Comment by davincent-ucl** [comment]
It's a docker image based on ubuntu:jammy.

**Comment by gauteh** [comment]
Ok. I think the assets are missing for the musl builds, probably better to install from source if you use pip on those platforms.

**Comment by davincent-ucl** [comment]
Thank you for your help

**Comment by TheSylex** [comment]
@gauteh all I do to install the package is pip install .
I can try to help tho

**Comment by TheSylex** [comment]
![image](https://github.com/user-attachments/assets/78163777-365b-4840-b5c0-6c1e64f18435)
No problem on my side with pip install . on main branch
Using NixOS, but I do not have any problem either with ubuntu in a docker.

**Comment by TheSylex** [comment]
![image](https://github.com/user-attachments/assets/c5e66784-325c-4d1b-bd14-e02f5dde2cff)
no problems either with the pypi version

it must definitely be related to musl

**Comment by TheSylex** [comment]
Okay, I'm a dumbass, it is in fact giving a problem now about not finding the mask for me too

**Comment by TheSylex** [comment]
@gauteh do you have any means for faster comms? discord/slack/gitter idk

**Comment by TheSylex** [comment]
Installing from local is fine, doing `pip install .` and then creating a mask works perfectly.
However as @davincent-ucl mentioned, installing through pypi gives the error of not finding the mask. So I'd assume this may be related to the publishing actions.
I do not have experience with that but I can still try to help, ping me whenever you need smth.

**Comment by gauteh** [comment]
I yanked the 0.9.0 release from pypi, we're not able to publish a correct version there until #31 is fixed. The only wheels that were published where macos ones (large enough to contain the masks) and musl-wheels, too small to contain the masks. Which probably means you are on a musl-platform of sorts? I don't think we should distribute those wheels, people can install from source on those platforms (or use conda).

**Comment by gauteh** [comment]
I have pushed a new version without the faulty wheels, the package should now be built from source.
